### PR TITLE
Merged devel into master

### PR DESCRIPTION
**Pull request by eljrax**
Merge devel into master.
Includes version bump to 0.4.0
New plugin: raxmon_autoscale

### CODE REVIEW

**Comment by Teddy-Schmitz** [comment]
We need to take this oppurtunity to update the documentation for your new plugin as well as fix any errors that might be there.  I'll submit some pull requests to clean up the older documentation can you add some notes on how to configure your plugin?

**Comment by Teddy-Schmitz** [comment]
It also looks like one test fails, test_add_entity_check

**Comment by eljrax** [comment]
@Teddy-Schmitz I don't get any test failures when I run `make test` - what are you seeing?

**Comment by eljrax** [comment]
@Teddy-Schmitz  so the tests all passes now. But now that Travis is enabled, it's choking on a few PEP8 things here and there.
I'll get those sorted.

**Comment by eljrax** [comment]
2.7 passes the checks - 2.6 are having some issues with some of the pyrax dependencies.
I added importlib to requirements-dev.txt to get over the first hump.

I've seen references alluding to that the piece it's failing on was only backported to 2.7, but the build works just fine on a 2.6 box I'm testing on.
Is the Travis box OK?

**Comment by Teddy-Schmitz** [comment]
Ya, looks like this module might fix the issue.

https://pypi.python.org/pypi/total-ordering

Can you try adding it your branch and seeing if it fixes the issue?

**Comment by Teddy-Schmitz** [comment]
O and ya sorry about that, Travis-CI should have been enabled this whole time.  I only just noticed it wasn't when I was cleaning things up for release.

**Comment by eljrax** [comment]
That doesn't seem to have solved anything. After a pip install --upgrade -r requirements-dev.txt it still fails.

Are we sure pyrax (or rather, its dependencies) is still compatible with 2.6? 

Here's a run from a docker container with slightly dated dependencies where upgrading python-keystoneclient results in this error:
```
[root@391b4ebaae89 rax-autoscaler]# make test 2>&1  | tail -1
OK
[root@391b4ebaae89 rax-autoscaler]# pip install --upgrade python-keystoneclient
...
[root@391b4ebaae89 rax-autoscaler]# make test 2>&1  | tail -1
...
    from oslo_config import cfg
  File "/usr/lib/python2.6/site-packages/oslo_config/cfg.py", line 635, in <module>
    @functools.total_ordering
AttributeError: 'module' object has no attribute 'total_ordering'
make: *** [test] Error 1
```

**Comment by Teddy-Schmitz** [comment]
Hmm, well it definitely worked before as we had Travis working before and everything was working good.  I'll look into this tomorrow and see if I can figure out whats going on.  I would prefer not to drop 2.6 support as I believe RHEL/CENTOS 5 both use it.  If I can't figure it out then we can drop support for it, though I would be rather disappointed if it's pyrax's fault.

**Comment by eljrax** [comment]
This is the change:
https://github.com/openstack/oslo.config/commit/9470f19eacb99425055946bd4a6079b71406ff1b 
oslo.config has explicitly dropped 2.6 support, and pyrax does rely on oslo.config
So python 2.6 would have worked before November last year.

**Pull request merged**
