### PR TITLE
Add support for supplying multiple load balancers to check for health…

### PR DESCRIPTION
**Pull request by eljrax**
…y node count before scaling down

This is useful for users who has more than one load balancer per scaling group (which is supported), to load balance multiple applications.

### CODE REVIEW

**Comment by Teddy-Schmitz** [comment]
Can you add a test that provides multiple load balancers, so we make sure that future changes allow for single as well as multi-loadbalancer configurations.

**Comment by eljrax** [comment]
Tests covering both single and multiple load-balancers added!

**Comment by Teddy-Schmitz** [comment]
Great thanks!  I think the only major test missing is creating the check if it doesn't exist.  But other then that I think it's good to merge in.

**Comment by eljrax** [comment]
The functionality to add the monitor if it doesn't exist is actually inherited from raxas/core_plugins/raxmon.py add_entity_checks()..

So seeing how this code exists in two places (and bound to be useful for other cloud monitoring plugins), we should probably look at making this a common function?

**Comment by eljrax** [comment]
Monitor adding test added

**Comment by Teddy-Schmitz** [comment]
Kool, your right we should have a common utilities for plugins function somewhere but for now I think we are good to merge your code.  Feel free to merge it in when you like.

**Pull request merged**
